[package]
name = "grayt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
glam = "0.21"
rand = "0.8"
image = "0.24"
num-traits = "0.2"